<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-829SJ9A" failures="3" tests="5" name="BankingApp Test(failed)" time="158.46" errors="0" timestamp="2021-02-01T11:57:33 IST">
  <testcase classname="com.inetbankingappV1.TestCases.TC_loginTest_001" name="loginTest" time="14.34"/>
  <testcase classname="com.inetbankingappV1.TestCases.TC_LoginDDT_002" name="loginDDT" time="10.368">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetbankingappV1.TestCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.inetbankingappV1.TestCases.TC_LoginDDT_002" name="loginDDT" time="7.563">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetbankingappV1.TestCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.inetbankingappV1.TestCases.TC_LoginDDT_002" name="loginDDT" time="6.292">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetbankingappV1.TestCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.inetbankingappV1.TestCases.TC_AddCustomerTest_003" name="addNewCustomer" time="30.162"/>
</testsuite> <!-- BankingApp Test(failed) -->
